Improve the creation of customer based on source instead of token
killbill/killbill-stripe-plugin pull request #44
Opened 2022-01-10 10:07 UTC by Jimmy-Newtron

I want to add a SEPA debit payment method in an easy way like you can do with a Credit Card Token

The current implementation is enhanced by allowing the user to pass a Stripe **source** ID of the form _src_xxxx_ 

The unit test added allows to test the addition of a SEPA debit bank account and execute 2 payments

As per Stripe documentation 
> Source objects allow you to accept a variety of payment methods. They represent a customer's payment instrument

So using sources we can add as well other form of payments like GooglePay, ApplePay, AliPay, vouchers, etc...

2022-01-10 10:08 UTC, Jimmy-Newtron commented
![image](https://user-images.githubusercontent.com/24460646/148748581-058fc992-d212-46b0-8ebb-141e6f94a8d3.png)

2022-01-10 10:13 UTC, Jimmy-Newtron commented
@pierre this is the second contribution I was willing to add before creating a new release

2022-01-11 06:42 UTC, pierre reviewed
I just have a couple of small comments.

2022-01-11 06:42 UTC, pierre commented on src/main/java/org/killbill/billing/plugin/stripe/StripePaymentPluginApi.java
> +          // The id to charge is the one-time token
Isn't this comment incorrect, now (e.g. when passing a source)?

2022-01-11 06:42 UTC, pierre commented on src/main/java/org/killbill/billing/plugin/stripe/StripePaymentPluginApi.java
> +    private String createStripeCustomer(final UUID kbAccountId, final CallContext context, final RequestOptions requestOptions,
For consistency in the order of arguments and style (see `executeFollowUpTransaction`):

```
private String createStripeCustomer(final UUID kbAccountId,
                                    final String paymentMethodIdInStripe,
                                    final String defaultStripeId,
                                    final RequestOptions requestOptions,
                                    final Iterable<PluginProperty> allProperties
                                    final CallContext context) throws StripeException, PaymentPluginApiException {
```

2022-01-11 08:11 UTC, pierre requested changes
You need to modify the callers as well...

2022-01-11 08:36 UTC, Jimmy-Newtron commented
> You need to modify the callers as well...

I need a coffee :)
Merci

2022-01-11 13:23 UTC, pierre approved these changes

2022-01-11 13:24 UTC, merged

2022-01-11 13:24 UTC, pierre commented
Thanks!